import { useChecklist } from "@/hooks/useChecklist";
import { cn } from "@/lib/utils";
import { FileText, CreditCard, Luggage, Smartphone, HeartPulse, GraduationCap, Dumbbell } from "lucide-react";
const groups=[
{icon:FileText,title:"Documentos",items:["Passaporte válido","Documentos do intercâmbio","Seguro viagem","Vouchers e reservas","Cópias digitais salvas"]},
{icon:GraduationCap,title:"Intercâmbio",items:["Curso confirmado","Acomodação em Liverpool","Calendário de aulas","Comprovantes financeiros/documentais","Plano para os 30 dias"]},
{icon:CreditCard,title:"Dinheiro & cartões",items:["Meta do Cofrinho","Cartão internacional principal","Cartão backup","Planejamento de EUR","Planejamento de GBP"]},
{icon:Luggage,title:"Mala",items:["Roupas para outono europeu","Calçado confortável","Casaco impermeável","Adaptadores","Espaço para o kimono"]},
{icon:Smartphone,title:"Tecnologia",items:["eSIM/chip","Carregador portátil","Mapas offline","Apps de trem/transporte","Acesso ao site da viagem"]},
{icon:Dumbbell,title:"Jiu-jitsu em Liverpool",items:["Validar academia/equipe","Confirmar drop-in ou plano mensal","Checar horários","Kimono/faixa","Lavanderia perto da acomodação"]},
{icon:HeartPulse,title:"Saúde & segurança",items:["Seguro com cobertura adequada","Remédios pessoais","Contatos de emergência","Endereços importantes","Rotina segura de volta à noite"]},
];
export const FullChecklist=()=>{const{checked,toggle}=useChecklist("full");return <section id="checklist" className="bg-secondary/40 border-y border-border/60"><div className="container mx-auto px-6 py-16 md:py-24 max-w-6xl"><div className="mb-12 max-w-2xl"><p className="text-xs tracking-[0.3em] uppercase text-olive mb-3">Preparação</p><h2 className="font-display text-4xl md:text-5xl text-ink">Checklist completo</h2><p className="mt-4 text-muted-foreground">Nesta primeira publicação, as marcações ficam salvas no aparelho. Depois passam para a conta individual e para o checklist compartilhado.</p></div><div className="grid md:grid-cols-2 gap-5">{groups.map(g=><div key={g.title} className="rounded-3xl bg-card border border-border/60 p-7 shadow-card"><div className="flex items-center gap-3 mb-5"><div className="w-10 h-10 rounded-xl bg-olive/10 flex items-center justify-center"><g.icon className="h-5 w-5 text-olive"/></div><h3 className="font-display text-2xl text-ink">{g.title}</h3></div><ul className="space-y-2.5">{g.items.map(it=>{const id=`${g.title}-${it}`;const on=!!checked[id];return <li key={id}><label className="flex items-start gap-3 cursor-pointer group"><input type="checkbox" checked={on} onChange={()=>toggle(id)} className="sr-only"/><span className={cn("mt-0.5 flex-shrink-0 h-5 w-5 rounded-md border-2 flex items-center justify-center transition-colors",on?"bg-olive border-olive":"border-olive/40 group-hover:border-olive")}>{on&&<svg viewBox="0 0 16 16" className="h-3 w-3 text-primary-foreground" fill="none" stroke="currentColor" strokeWidth={3}><path d="M3 8.5l3 3 7-7" strokeLinecap="round" strokeLinejoin="round"/></svg>}</span><span className={cn("text-sm text-foreground/85 leading-snug",on&&"line-through opacity-60")}>{it}</span></label></li>})}</ul></div>)}</div></div></section>};