import { Link } from "react-router-dom";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Bell, ListChecks, PiggyBank, ReceiptText, ShieldCheck, Sparkles, UserRound } from "lucide-react";

const actions = [
  { to: "/minha-viagem", title: "Cofrinho individual", text: "Meta, guardado, pendente e histórico de lançamentos.", icon: PiggyBank },
  { to: "/#checklist", title: "Checklist pessoal", text: "Marcar e desmarcar sua preparação para a viagem.", icon: ListChecks },
  { to: "/minha-viagem", title: "Prioridades pessoais", text: "Imperdível, desejável e opcional para o otimizador de rota.", icon: Sparkles },
  { to: "/minha-viagem", title: "Preferências de alerta", text: "Voos, câmbio, prazos, hospedagem e experiências.", icon: Bell },
  { to: "/rateio", title: "Rateio da viagem", text: "Quem pagou, quem participa e quem deve a quem.", icon: ReceiptText },
];

const Grupo=()=>{const{user,profile,roles,loading,isOrganizadora,signOut}=useAuth();if(loading)return <div className="min-h-screen grid place-items-center text-muted-foreground">Carregando…</div>;if(!user)return <div className="min-h-screen grid place-items-center px-6 text-center"><div><h1 className="font-display text-4xl text-ink">Área do grupo</h1><p className="text-muted-foreground mt-2 mb-6">Entre para acessar sua conta da viagem.</p><Link to="/auth"><Button className="rounded-full">Entrar</Button></Link></div></div>;const label=profile?.display_name||user.user_metadata?.full_name||user.email;return <div className="min-h-screen bg-background"><div className="container mx-auto px-6 py-14 max-w-4xl"><Link to="/" className="text-sm text-olive hover:underline">← Voltar ao roteiro</Link><p className="text-xs tracking-[0.3em] uppercase text-olive mt-8 mb-3">Área privada</p><h1 className="font-display text-4xl md:text-5xl text-ink">O grupo da viagem</h1><div className="mt-8 rounded-3xl bg-card border border-border/60 p-7 shadow-card"><div className="flex items-center gap-4"><div className="h-12 w-12 rounded-2xl bg-olive/10 grid place-items-center"><UserRound className="h-6 w-6 text-olive"/></div><div className="flex-1 min-w-0"><p className="font-display text-2xl text-ink truncate">{label}</p><p className="text-sm text-muted-foreground truncate">{user.email}</p></div>{isOrganizadora&&<span className="inline-flex items-center gap-1 rounded-full bg-gold/15 border border-gold/30 px-3 py-1 text-xs text-olive"><ShieldCheck className="h-3.5 w-3.5"/>Organizadora</span>}</div><div className="mt-6 pt-5 border-t border-border/60 text-sm text-foreground/75"><p><strong className="text-ink">Papel:</strong> {isOrganizadora?"organizadora":roles[0]||"viajante"}</p><p className="mt-2">Seus dados pessoais ficam separados dos dados compartilhados da viagem.</p></div></div><div className="grid md:grid-cols-2 gap-4 mt-6">{actions.map(a=><Link key={a.title} to={a.to} className="group rounded-3xl border border-border/60 bg-card p-6 shadow-card hover:border-gold/50 hover:shadow-soft transition-all"><div className="h-10 w-10 rounded-xl bg-gold/15 grid place-items-center mb-4"><a.icon className="h-5 w-5 text-olive"/></div><h2 className="font-display text-2xl text-ink">{a.title}</h2><p className="text-sm text-muted-foreground mt-2">{a.text}</p></Link>)}</div><Button variant="ghost" onClick={signOut} className="mt-8">Sair da conta</Button></div></div>};
export default Grupo;