name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR merge
        run: |
          git clone --quiet "https://github.com/${GITHUB_REPOSITORY}.git" .
          git fetch --quiet origin "refs/pull/${{ github.event.pull_request.number }}/merge:pr-merge" || true
          if [ -n "${{ github.event.pull_request.number }}" ]; then git checkout --quiet pr-merge; else git checkout --quiet "$GITHUB_SHA"; fi
      - name: Install
        run: npm install --silent --no-audit --no-fund
      - name: Build app
        run: npm run build
